'use client'

import * as React from 'react'
import { useState, useEffect, useCallback } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip'
import { Switch } from '@/components/ui/switch'
import { 
  Wand2, 
  Copy, 
  Check, 
  RefreshCw, 
  Barcode, 
  Tag,
  Settings,
  ExternalLink,
  AlertCircle,
  Info
} from 'lucide-react'
import { cn } from '@/lib/utils'
import {
  generateSKU,
  generateBarcode,
  generateIdentifiers,
  validateSKU,
  validateBarcode,
  SKU_TEMPLATES,
  BARCODE_FORMATS,
  type SKUGeneratorConfig,
  type BarcodeGeneratorConfig,
} from '@/lib/utils/sku-barcode-generator'

interface SKUBarcodeGeneratorProps {
  productName?: string
  currentSKU?: string
  currentBarcode?: string
  externalSKU?: string  // SKU from external platform
  externalBarcode?: string  // Barcode from external platform
  externalPlatform?: string  // Platform name (salla, zid, etc.)
  onSKUChange: (sku: string, autoGenerated: boolean) => void
  onBarcodeChange: (barcode: string, barcodeType: string, autoGenerated: boolean) => void
  existingSkus?: string[]
  existingBarcodes?: string[]
  disabled?: boolean
  skuConfig?: Partial<SKUGeneratorConfig>
  barcodeConfig?: Partial<BarcodeGeneratorConfig>
}

export function SKUBarcodeGenerator({
  productName,
  currentSKU = '',
  currentBarcode = '',
  externalSKU,
  externalBarcode,
  externalPlatform,
  onSKUChange,
  onBarcodeChange,
  existingSkus = [],
  existingBarcodes = [],
  disabled = false,
  skuConfig,
  barcodeConfig,
}: SKUBarcodeGeneratorProps) {
  const [sku, setSku] = useState(currentSKU)
  const [barcode, setBarcode] = useState(currentBarcode)
  const [barcodeType, setBarcodeType] = useState<string>('EAN13')
  const [skuCopied, setSkuCopied] = useState(false)
  const [barcodeCopied, setBarcodeCopied] = useState(false)
  const [skuErrors, setSkuErrors] = useState<string[]>([])
  const [barcodeErrors, setBarcodeErrors] = useState<string[]>([])
  const [useExternalSKU, setUseExternalSKU] = useState(false)
  const [useExternalBarcode, setUseExternalBarcode] = useState(false)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [selectedSkuTemplate, setSelectedSkuTemplate] = useState<string>('simple')
  const [selectedBarcodeFormat, setSelectedBarcodeFormat] = useState<string>('INTERNAL')
  const [customPrefix, setCustomPrefix] = useState('')

  // Update internal state when props change
  useEffect(() => {
    setSku(currentSKU)
  }, [currentSKU])

  useEffect(() => {
    setBarcode(currentBarcode)
  }, [currentBarcode])

  // Validate SKU on change
  useEffect(() => {
    if (sku) {
      const validation = validateSKU(sku)
      setSkuErrors(validation.errors)
    } else {
      setSkuErrors([])
    }
  }, [sku])

  // Validate barcode on change
  useEffect(() => {
    if (barcode) {
      const validation = validateBarcode(barcode)
      setBarcodeErrors(validation.errors)
      if (validation.detectedType) {
        setBarcodeType(validation.detectedType)
      }
    } else {
      setBarcodeErrors([])
    }
  }, [barcode])

  // Handle SKU generation
  const handleGenerateSKU = useCallback(() => {
    const template = SKU_TEMPLATES[selectedSkuTemplate as keyof typeof SKU_TEMPLATES]
    const config = {
      ...template?.config,
      ...skuConfig,
      prefix: customPrefix || template?.config.prefix || 'PROD',
    }
    
    const newSku = generateSKU(productName, config, existingSkus)
    setSku(newSku)
    onSKUChange(newSku, true)
  }, [productName, selectedSkuTemplate, customPrefix, skuConfig, existingSkus, onSKUChange])

  // Handle barcode generation
  const handleGenerateBarcode = useCallback(() => {
    const config: Partial<BarcodeGeneratorConfig> = {
      type: selectedBarcodeFormat as any,
      ...barcodeConfig,
    }
    
    const result = generateBarcode(config, existingBarcodes)
    setBarcode(result.barcode)
    setBarcodeType(result.type)
    onBarcodeChange(result.barcode, result.type, true)
  }, [selectedBarcodeFormat, barcodeConfig, existingBarcodes, onBarcodeChange])

  // Handle generate both
  const handleGenerateBoth = useCallback(() => {
    handleGenerateSKU()
    handleGenerateBarcode()
  }, [handleGenerateSKU, handleGenerateBarcode])

  // Handle using external SKU
  const handleUseExternalSKU = useCallback((use: boolean) => {
    setUseExternalSKU(use)
    if (use && externalSKU) {
      setSku(externalSKU)
      onSKUChange(externalSKU, false)
    }
  }, [externalSKU, onSKUChange])

  // Handle using external barcode
  const handleUseExternalBarcode = useCallback((use: boolean) => {
    setUseExternalBarcode(use)
    if (use && externalBarcode) {
      setBarcode(externalBarcode)
      const validation = validateBarcode(externalBarcode)
      onBarcodeChange(externalBarcode, validation.detectedType || 'UNKNOWN', false)
    }
  }, [externalBarcode, onBarcodeChange])

  // Handle manual SKU change
  const handleSkuInputChange = useCallback((value: string) => {
    setSku(value)
    onSKUChange(value, false)
  }, [onSKUChange])

  // Handle manual barcode change
  const handleBarcodeInputChange = useCallback((value: string) => {
    setBarcode(value)
    const validation = validateBarcode(value)
    onBarcodeChange(value, validation.detectedType || barcodeType, false)
  }, [barcodeType, onBarcodeChange])

  // Copy to clipboard
  const copyToClipboard = async (text: string, type: 'sku' | 'barcode') => {
    await navigator.clipboard.writeText(text)
    if (type === 'sku') {
      setSkuCopied(true)
      setTimeout(() => setSkuCopied(false), 2000)
    } else {
      setBarcodeCopied(true)
      setTimeout(() => setBarcodeCopied(false), 2000)
    }
  }

  return (
    <div className="space-y-4">
      {/* External Platform Notice */}
      {externalPlatform && (externalSKU || externalBarcode) && (
        <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
          <div className="flex items-start gap-3">
            <ExternalLink className="h-5 w-5 text-blue-600 mt-0.5" />
            <div className="flex-1">
              <p className="text-sm font-medium text-blue-800">
                External identifiers from {externalPlatform.charAt(0).toUpperCase() + externalPlatform.slice(1)}
              </p>
              <div className="mt-2 space-y-2">
                {externalSKU && (
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-blue-600">Platform SKU: <code className="bg-blue-100 px-1.5 py-0.5 rounded">{externalSKU}</code></span>
                    <Switch
                      checked={useExternalSKU}
                      onCheckedChange={handleUseExternalSKU}
                      disabled={disabled}
                    />
                  </div>
                )}
                {externalBarcode && (
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-blue-600">Platform Barcode: <code className="bg-blue-100 px-1.5 py-0.5 rounded">{externalBarcode}</code></span>
                    <Switch
                      checked={useExternalBarcode}
                      onCheckedChange={handleUseExternalBarcode}
                      disabled={disabled}
                    />
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* SKU Field */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label htmlFor="sku" className="flex items-center gap-2">
            <Tag className="h-4 w-4 text-gray-500" />
            SKU (Stock Keeping Unit)
          </Label>
          <TooltipProvider delayDuration={300}>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="h-7 px-2 text-xs"
                  onClick={() => setSettingsOpen(true)}
                  disabled={disabled}
                >
                  <Settings className="h-3.5 w-3.5 mr-1" />
                  Settings
                </Button>
              </TooltipTrigger>
              <TooltipContent>Configure generation settings</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Input
              id="sku"
              value={sku}
              onChange={(e) => handleSkuInputChange(e.target.value.toUpperCase())}
              placeholder="Enter or generate SKU"
              className={cn(
                "pr-20 font-mono",
                skuErrors.length > 0 && "border-red-300 focus:border-red-500"
              )}
              disabled={disabled || useExternalSKU}
            />
            <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
              {sku && (
                <TooltipProvider delayDuration={300}>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        className="h-7 w-7 p-0"
                        onClick={() => copyToClipboard(sku, 'sku')}
                      >
                        {skuCopied ? (
                          <Check className="h-3.5 w-3.5 text-green-600" />
                        ) : (
                          <Copy className="h-3.5 w-3.5 text-gray-400" />
                        )}
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>Copy SKU</TooltipContent>
                  </Tooltip>
                </TooltipProvider>
              )}
            </div>
          </div>
          <TooltipProvider delayDuration={300}>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={handleGenerateSKU}
                  disabled={disabled || useExternalSKU}
                  className="shrink-0"
                >
                  <Wand2 className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>Generate SKU</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        {skuErrors.length > 0 && (
          <div className="flex items-center gap-1.5 text-xs text-red-600">
            <AlertCircle className="h-3.5 w-3.5" />
            {skuErrors[0]}
          </div>
        )}
      </div>

      {/* Barcode Field */}
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <Label htmlFor="barcode" className="flex items-center gap-2">
            <Barcode className="h-4 w-4 text-gray-500" />
            Barcode
          </Label>
          <Select
            value={selectedBarcodeFormat}
            onValueChange={setSelectedBarcodeFormat}
            disabled={disabled || useExternalBarcode}
          >
            <SelectTrigger className="w-[140px] h-7 text-xs">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(BARCODE_FORMATS).map(([key, format]) => (
                <SelectItem key={key} value={key} className="text-xs">
                  {format.name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Input
              id="barcode"
              value={barcode}
              onChange={(e) => handleBarcodeInputChange(e.target.value)}
              placeholder="Enter or generate barcode"
              className={cn(
                "pr-20 font-mono",
                barcodeErrors.length > 0 && "border-red-300 focus:border-red-500"
              )}
              disabled={disabled || useExternalBarcode}
            />
            <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-1">
              {barcode && (
                <>
                  <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-5">
                    {barcodeType}
                  </Badge>
                  <TooltipProvider delayDuration={300}>
                    <Tooltip>
                      <TooltipTrigger asChild>
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="h-7 w-7 p-0"
                          onClick={() => copyToClipboard(barcode, 'barcode')}
                        >
                          {barcodeCopied ? (
                            <Check className="h-3.5 w-3.5 text-green-600" />
                          ) : (
                            <Copy className="h-3.5 w-3.5 text-gray-400" />
                          )}
                        </Button>
                      </TooltipTrigger>
                      <TooltipContent>Copy Barcode</TooltipContent>
                    </Tooltip>
                  </TooltipProvider>
                </>
              )}
            </div>
          </div>
          <TooltipProvider delayDuration={300}>
            <Tooltip>
              <TooltipTrigger asChild>
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={handleGenerateBarcode}
                  disabled={disabled || useExternalBarcode}
                  className="shrink-0"
                >
                  <Wand2 className="h-4 w-4" />
                </Button>
              </TooltipTrigger>
              <TooltipContent>Generate Barcode</TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        {barcodeErrors.length > 0 && (
          <div className="flex items-center gap-1.5 text-xs text-red-600">
            <AlertCircle className="h-3.5 w-3.5" />
            {barcodeErrors[0]}
          </div>
        )}
      </div>

      {/* Generate Both Button */}
      <Button
        type="button"
        variant="outline"
        className="w-full"
        onClick={handleGenerateBoth}
        disabled={disabled || (useExternalSKU && useExternalBarcode)}
      >
        <RefreshCw className="h-4 w-4 mr-2" />
        Generate Both SKU & Barcode
      </Button>

      {/* Settings Dialog */}
      <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>SKU Generator Settings</DialogTitle>
            <DialogDescription>
              Configure how SKUs are generated for your products
            </DialogDescription>
          </DialogHeader>
          
          <div className="space-y-4 py-4">
            {/* SKU Template */}
            <div className="space-y-2">
              <Label>SKU Template</Label>
              <Select value={selectedSkuTemplate} onValueChange={setSelectedSkuTemplate}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(SKU_TEMPLATES).map(([key, template]) => (
                    <SelectItem key={key} value={key}>
                      <div className="flex flex-col">
                        <span>{template.name}</span>
                        <span className="text-xs text-muted-foreground">{template.description}</span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Custom Prefix */}
            <div className="space-y-2">
              <Label>Custom Prefix</Label>
              <Input
                value={customPrefix}
                onChange={(e) => setCustomPrefix(e.target.value.toUpperCase())}
                placeholder="Leave empty to use template default"
                maxLength={10}
              />
              <p className="text-xs text-muted-foreground">
                Override the default prefix in the template
              </p>
            </div>

            {/* Preview */}
            <div className="bg-gray-50 rounded-lg p-3">
              <Label className="text-xs text-gray-500">Preview</Label>
              <div className="font-mono text-sm mt-1">
                {generateSKU(productName || 'Product', {
                  ...SKU_TEMPLATES[selectedSkuTemplate as keyof typeof SKU_TEMPLATES]?.config,
                  prefix: customPrefix || SKU_TEMPLATES[selectedSkuTemplate as keyof typeof SKU_TEMPLATES]?.config.prefix,
                })}
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setSettingsOpen(false)}>
              Close
            </Button>
            <Button onClick={() => {
              handleGenerateSKU()
              setSettingsOpen(false)
            }}>
              Apply & Generate
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

/**
 * Simplified SKU input with inline generation
 */
interface SKUInputProps {
  value: string
  onChange: (value: string) => void
  productName?: string
  existingSkus?: string[]
  disabled?: boolean
  error?: string
}

export function SKUInput({
  value,
  onChange,
  productName,
  existingSkus = [],
  disabled = false,
  error,
}: SKUInputProps) {
  const [copied, setCopied] = useState(false)

  const handleGenerate = () => {
    const newSku = generateSKU(productName, { prefix: 'PROD' }, existingSkus)
    onChange(newSku)
  }

  const handleCopy = async () => {
    if (value) {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="space-y-1.5">
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Input
            value={value}
            onChange={(e) => onChange(e.target.value.toUpperCase())}
            placeholder="SKU"
            className={cn(
              "font-mono",
              error && "border-red-300"
            )}
            disabled={disabled}
          />
          {value && (
            <Button
              type="button"
              variant="ghost"
              size="sm"
              className="absolute right-1 top-1/2 -translate-y-1/2 h-7 w-7 p-0"
              onClick={handleCopy}
            >
              {copied ? (
                <Check className="h-3.5 w-3.5 text-green-600" />
              ) : (
                <Copy className="h-3.5 w-3.5 text-gray-400" />
              )}
            </Button>
          )}
        </div>
        <Button
          type="button"
          variant="outline"
          size="icon"
          onClick={handleGenerate}
          disabled={disabled}
        >
          <Wand2 className="h-4 w-4" />
        </Button>
      </div>
      {error && (
        <p className="text-xs text-red-600">{error}</p>
      )}
    </div>
  )
}

/**
 * Simplified Barcode input with inline generation
 */
interface BarcodeInputProps {
  value: string
  onChange: (value: string, type: string) => void
  existingBarcodes?: string[]
  disabled?: boolean
  error?: string
}

export function BarcodeInput({
  value,
  onChange,
  existingBarcodes = [],
  disabled = false,
  error,
}: BarcodeInputProps) {
  const [copied, setCopied] = useState(false)
  const [detectedType, setDetectedType] = useState<string>('—')

  useEffect(() => {
    if (value) {
      const validation = validateBarcode(value)
      setDetectedType(validation.detectedType || '—')
    } else {
      setDetectedType('—')
    }
  }, [value])

  const handleGenerate = () => {
    const result = generateBarcode({ type: 'INTERNAL' }, existingBarcodes)
    onChange(result.barcode, result.type)
  }

  const handleCopy = async () => {
    if (value) {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="space-y-1.5">
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Input
            value={value}
            onChange={(e) => {
              const newValue = e.target.value
              const validation = validateBarcode(newValue)
              onChange(newValue, validation.detectedType || 'UNKNOWN')
            }}
            placeholder="Barcode"
            className={cn(
              "font-mono pr-24",
              error && "border-red-300"
            )}
            disabled={disabled}
          />
          <div className="absolute right-1 top-1/2 -translate-y-1/2 flex items-center gap-1">
            {value && (
              <>
                <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-5">
                  {detectedType}
                </Badge>
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0"
                  onClick={handleCopy}
                >
                  {copied ? (
                    <Check className="h-3.5 w-3.5 text-green-600" />
                  ) : (
                    <Copy className="h-3.5 w-3.5 text-gray-400" />
                  )}
                </Button>
              </>
            )}
          </div>
        </div>
        <Button
          type="button"
          variant="outline"
          size="icon"
          onClick={handleGenerate}
          disabled={disabled}
        >
          <Wand2 className="h-4 w-4" />
        </Button>
      </div>
      {error && (
        <p className="text-xs text-red-600">{error}</p>
      )}
    </div>
  )
}

